name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Install Homebrew
      shell: bash
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> ~/.bash_profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version

    - name: Install aws iam authenticator
      shell: bash
      run: brew install aws-iam-authenticator

    - name: Install awscli
      shell: bash
      run: brew install awscli

    - name: Install kubectl
      shell: bash
      run: brew install kubernetes-cli

    - name: Install wget
      shell: bash
      run: brew install wget

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.18.0"

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ">= 1.1.2"
        terraform_wrapper: false

    - name: Terraform init
      shell: bash
      run: terraform init
