name: Terraform Deploy
on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.8
      - name: Terraform init
        run: terraform init
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: 'v1.25.2'
          kubernetes version: 'v1.23.0'
          github token: ${{ secrets.TOKEN }}
      - name: Install socat
        run: sudo apt install socat
      - name: Try cluster
        run: kubectl get pods -A
      - name: Terraform deploy
        run: terraform apply --auto-approve
      - name: Terraform test
        run: cd test && go test -v
      - name: Terraform Destroy
        run: terraform destroy --auto-approve